name: Build and Push Nutanix Field DNS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKER_API_VERSION: "1.41"

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Free Port 53 and Fix DNS
      run: |
        # 1. Stoppe den blockierenden Dienst
        sudo systemctl stop systemd-resolved
        sudo systemctl disable systemd-resolved

        # 2. Lösche den (potenziell kaputten) Symlink
        sudo rm -f /etc/resolv.conf

        # 3. Erstelle eine echte Datei mit externem DNS
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf

        # 4. Kurzer Test, ob das Internet noch da ist
        ping -c 1 google.com

    - name: Build DNS Image
      run: make build

    - name: Run DNS Service and Health Check
      run: |
        make run
        sleep 5
        make test
        make stop

    - name: Build and Push to GHCR
      # Wichtig: Hier wird die iac-toolbox (Ansible) getriggert
      run: make push
